# makefile created automaticaly by LFMakeMaker
# LFMakeMaker 1.6 (May  9 2022 15:11:43) (c)LFSoft 1997

gotoall: all

# Warning : 'string' can't be located for this node.
# Warning : 'cstring' can't be located for this node.
# Warning : 'cstdarg' can't be located for this node.

#The compiler (may be customized for compiler's options).
cc=c++ -Wall -O2 -I../shared
opts=$(shell pkg-config --libs openssl)

../shared/Helpers.o : ../shared/Helpers.cpp ../shared/Helpers.h \
  Makefile 
	$(cc) -c -o ../shared/Helpers.o ../shared/Helpers.cpp $(opts) 

# Warning : 'filesystem' can't be located for this node.
# Warning : 'string' can't be located for this node.
../shared/NoSlashPath.o : ../shared/NoSlashPath.cpp \
  ../shared/NoSlashPath.h Makefile 
	$(cc) -c -o ../shared/NoSlashPath.o ../shared/NoSlashPath.cpp \
  $(opts) 

# Warning : 'string' can't be located for this node.
# Warning : 'iostream' can't be located for this node.
# Warning : 'sys/types.h' can't be located for this node.
# Warning : 'sys/socket.h' can't be located for this node.
# Warning : 'sys/un.h' can't be located for this node.
../shared/SocketHelpers.o : ../shared/SocketHelpers.cpp \
  ../shared/SocketHelpers.h Makefile 
	$(cc) -c -o ../shared/SocketHelpers.o \
  ../shared/SocketHelpers.cpp $(opts) 

# Warning : 'filesystem' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'filesystem' can't be located for this node.
# Warning : 'fstream' can't be located for this node.
# Warning : 'vector' can't be located for this node.
# Warning : 'map' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'list' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'iostream' can't be located for this node.
# Warning : 'filesystem' can't be located for this node.
# Warning : 'list' can't be located for this node.
# Warning : 'cassert' can't be located for this node.
Directory.o : Directory.cpp Directory.h Item.h File.h FindDuplicate.h \
  Config.h ../shared/SocketHelpers.h ../shared/NoSlashPath.h Makefile 
	$(cc) -c -o Directory.o Directory.cpp $(opts) 

# Warning : 'string' can't be located for this node.
# Warning : 'filesystem' can't be located for this node.
# Warning : 'fstream' can't be located for this node.
# Warning : 'filesystem' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'vector' can't be located for this node.
# Warning : 'map' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'list' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'openssl/evp.h' can't be located for this node.
# Warning : 'fstream' can't be located for this node.
# Warning : 'iostream' can't be located for this node.
# Warning : 'cstring' can't be located for this node.
File.o : File.cpp File.h Item.h Directory.h FindDuplicate.h Config.h \
  ../shared/SocketHelpers.h ../shared/NoSlashPath.h Makefile 
	$(cc) -c -o File.o File.cpp $(opts) 

# Warning : 'filesystem' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'filesystem' can't be located for this node.
# Warning : 'fstream' can't be located for this node.
# Warning : 'vector' can't be located for this node.
# Warning : 'map' can't be located for this node.
# Warning : 'iostream' can't be located for this node.
FindDuplicate.o : FindDuplicate.cpp Config.h FindDuplicate.h File.h \
  Item.h ../shared/NoSlashPath.h Makefile 
	$(cc) -c -o FindDuplicate.o FindDuplicate.cpp $(opts) 

# Warning : 'iostream' can't be located for this node.
# Warning : 'iomanip' can't be located for this node.
# Warning : 'fstream' can't be located for this node.
# Warning : 'cstring' can't be located for this node.
# Warning : 'cassert' can't be located for this node.
# Warning : 'unistd.h' can't be located for this node.
# Warning : 'libgen.h' can't be located for this node.
# Warning : 'poll.h' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'filesystem' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'filesystem' can't be located for this node.
# Warning : 'fstream' can't be located for this node.
# Warning : 'vector' can't be located for this node.
# Warning : 'map' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'list' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'sys/types.h' can't be located for this node.
# Warning : 'sys/socket.h' can't be located for this node.
# Warning : 'sys/un.h' can't be located for this node.
MerDeGlace.o : MerDeGlace.cpp Config.h Directory.h Item.h File.h \
  FindDuplicate.h SocketInterface.h ../shared/NoSlashPath.h \
  ../shared/Helpers.h ../shared/Version.h Makefile 
	$(cc) -c -o MerDeGlace.o MerDeGlace.cpp $(opts) 

# Warning : 'string' can't be located for this node.
# Warning : 'sys/types.h' can't be located for this node.
# Warning : 'sys/socket.h' can't be located for this node.
# Warning : 'sys/un.h' can't be located for this node.
# Warning : 'filesystem' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'filesystem' can't be located for this node.
# Warning : 'fstream' can't be located for this node.
# Warning : 'vector' can't be located for this node.
# Warning : 'map' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'list' can't be located for this node.
# Warning : 'string' can't be located for this node.
# Warning : 'iostream' can't be located for this node.
# Warning : 'map' can't be located for this node.
# Warning : 'cerrno' can't be located for this node.
# Warning : 'cstdlib' can't be located for this node.
# Warning : 'cassert' can't be located for this node.
# Warning : 'unistd.h' can't be located for this node.
# Warning : 'poll.h' can't be located for this node.
SocketInterface.o : SocketInterface.cpp SocketInterface.h Config.h \
  Directory.h Item.h File.h FindDuplicate.h ../shared/SocketHelpers.h \
  ../shared/NoSlashPath.h Makefile 
	$(cc) -c -o SocketInterface.o SocketInterface.cpp $(opts) 

../MerDeGlaced : SocketInterface.o MerDeGlace.o FindDuplicate.o File.o \
  Directory.o ../shared/SocketHelpers.o ../shared/NoSlashPath.o \
  ../shared/Helpers.o Makefile 
	 $(cc) -o ../MerDeGlaced SocketInterface.o MerDeGlace.o \
  FindDuplicate.o File.o Directory.o ../shared/SocketHelpers.o \
  ../shared/NoSlashPath.o ../shared/Helpers.o $(opts) 

all: ../MerDeGlaced 
